#!/usr/bin/env node
// ABIs are generated from forge's artefacts, never hand-copied.
// A hand-written slice drifts the moment a signature changes, and a gate that only
// compares argument counts cannot see a type drift.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = join(HERE, "..", "..", "out");
const DEST = join(HERE, "..", "src", "generated");

const WANT = ["LevVault", "Bonding", "LaunchToken", "FeeVault", "VaultFactory"];

if (!existsSync(OUT)) {
  console.error(`\n  ABORT: ${OUT} does not exist — run \`forge build\` in the repo root first.\n`);
  process.exit(1);
}

mkdirSync(DEST, { recursive: true });
const parts = [
  "// GENERATED by scripts/gen-abi.mjs from forge artefacts. Do not edit.",
  "// Regenerate with `npm run abi` after any contract change.",
  "",
];
for (const name of WANT) {
  const p = join(OUT, `${name}.sol`, `${name}.json`);
  if (!existsSync(p)) {
    console.error(`\n  ABORT: no artefact for ${name} at ${p}\n`);
    process.exit(1);
  }
  const abi = JSON.parse(readFileSync(p, "utf8")).abi;
  parts.push(`export const ${name}Abi = ${JSON.stringify(abi)} as const;`);
}
writeFileSync(join(DEST, "abi.ts"), parts.join("\n") + "\n");
console.log(`  wrote ${WANT.length} ABIs -> src/generated/abi.ts`);
